# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chain.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chain.proto',
  package='chain',
  syntax='proto3',
  serialized_options=b'\n\024edu.sjsu.cs249.chainP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x63hain.proto\x12\x05\x63hain\"+\n\nIncRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x10\n\x08incValue\x18\x02 \x01(\x05\"\x1a\n\x0cHeadResponse\x12\n\n\x02rc\x18\x01 \x01(\r\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"(\n\x0bGetResponse\x12\n\n\x02rc\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\x05\";\n\rUpdateRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x10\n\x08newValue\x18\x02 \x01(\x05\x12\x0b\n\x03xid\x18\x03 \x01(\r\"\x1c\n\x0eUpdateResponse\x12\n\n\x02rc\x18\x01 \x01(\r\"\xac\x01\n\x14StateTransferRequest\x12\x35\n\x05state\x18\x01 \x03(\x0b\x32&.chain.StateTransferRequest.StateEntry\x12\x0b\n\x03xid\x18\x02 \x01(\r\x12\"\n\x04sent\x18\x03 \x03(\x0b\x32\x14.chain.UpdateRequest\x1a,\n\nStateEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\"#\n\x15StateTransferResponse\x12\n\n\x02rc\x18\x01 \x01(\r\"\x19\n\nAckRequest\x12\x0b\n\x03xid\x18\x01 \x01(\r\"\r\n\x0b\x41\x63kResponse2G\n\x10HeadChainReplica\x12\x33\n\tincrement\x12\x11.chain.IncRequest\x1a\x13.chain.HeadResponse2@\n\x10TailChainReplica\x12,\n\x03get\x12\x11.chain.GetRequest\x1a\x12.chain.GetResponse2\xba\x01\n\x07Replica\x12\x35\n\x06update\x12\x14.chain.UpdateRequest\x1a\x15.chain.UpdateResponse\x12J\n\rstateTransfer\x12\x1b.chain.StateTransferRequest\x1a\x1c.chain.StateTransferResponse\x12,\n\x03\x61\x63k\x12\x11.chain.AckRequest\x1a\x12.chain.AckResponseB\x18\n\x14\x65\x64u.sjsu.cs249.chainP\x01\x62\x06proto3'
)




_INCREQUEST = _descriptor.Descriptor(
  name='IncRequest',
  full_name='chain.IncRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='chain.IncRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='incValue', full_name='chain.IncRequest.incValue', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=65,
)


_HEADRESPONSE = _descriptor.Descriptor(
  name='HeadResponse',
  full_name='chain.HeadResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rc', full_name='chain.HeadResponse.rc', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=93,
)


_GETREQUEST = _descriptor.Descriptor(
  name='GetRequest',
  full_name='chain.GetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='chain.GetRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=120,
)


_GETRESPONSE = _descriptor.Descriptor(
  name='GetResponse',
  full_name='chain.GetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rc', full_name='chain.GetResponse.rc', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='chain.GetResponse.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=162,
)


_UPDATEREQUEST = _descriptor.Descriptor(
  name='UpdateRequest',
  full_name='chain.UpdateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='chain.UpdateRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='newValue', full_name='chain.UpdateRequest.newValue', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='xid', full_name='chain.UpdateRequest.xid', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=223,
)


_UPDATERESPONSE = _descriptor.Descriptor(
  name='UpdateResponse',
  full_name='chain.UpdateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rc', full_name='chain.UpdateResponse.rc', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=253,
)


_STATETRANSFERREQUEST_STATEENTRY = _descriptor.Descriptor(
  name='StateEntry',
  full_name='chain.StateTransferRequest.StateEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='chain.StateTransferRequest.StateEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='chain.StateTransferRequest.StateEntry.value', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=384,
  serialized_end=428,
)

_STATETRANSFERREQUEST = _descriptor.Descriptor(
  name='StateTransferRequest',
  full_name='chain.StateTransferRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='chain.StateTransferRequest.state', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='xid', full_name='chain.StateTransferRequest.xid', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sent', full_name='chain.StateTransferRequest.sent', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_STATETRANSFERREQUEST_STATEENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=428,
)


_STATETRANSFERRESPONSE = _descriptor.Descriptor(
  name='StateTransferResponse',
  full_name='chain.StateTransferResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rc', full_name='chain.StateTransferResponse.rc', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=430,
  serialized_end=465,
)


_ACKREQUEST = _descriptor.Descriptor(
  name='AckRequest',
  full_name='chain.AckRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='xid', full_name='chain.AckRequest.xid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=467,
  serialized_end=492,
)


_ACKRESPONSE = _descriptor.Descriptor(
  name='AckResponse',
  full_name='chain.AckResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=494,
  serialized_end=507,
)

_STATETRANSFERREQUEST_STATEENTRY.containing_type = _STATETRANSFERREQUEST
_STATETRANSFERREQUEST.fields_by_name['state'].message_type = _STATETRANSFERREQUEST_STATEENTRY
_STATETRANSFERREQUEST.fields_by_name['sent'].message_type = _UPDATEREQUEST
DESCRIPTOR.message_types_by_name['IncRequest'] = _INCREQUEST
DESCRIPTOR.message_types_by_name['HeadResponse'] = _HEADRESPONSE
DESCRIPTOR.message_types_by_name['GetRequest'] = _GETREQUEST
DESCRIPTOR.message_types_by_name['GetResponse'] = _GETRESPONSE
DESCRIPTOR.message_types_by_name['UpdateRequest'] = _UPDATEREQUEST
DESCRIPTOR.message_types_by_name['UpdateResponse'] = _UPDATERESPONSE
DESCRIPTOR.message_types_by_name['StateTransferRequest'] = _STATETRANSFERREQUEST
DESCRIPTOR.message_types_by_name['StateTransferResponse'] = _STATETRANSFERRESPONSE
DESCRIPTOR.message_types_by_name['AckRequest'] = _ACKREQUEST
DESCRIPTOR.message_types_by_name['AckResponse'] = _ACKRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IncRequest = _reflection.GeneratedProtocolMessageType('IncRequest', (_message.Message,), {
  'DESCRIPTOR' : _INCREQUEST,
  '__module__' : 'chain_pb2'
  # @@protoc_insertion_point(class_scope:chain.IncRequest)
  })
_sym_db.RegisterMessage(IncRequest)

HeadResponse = _reflection.GeneratedProtocolMessageType('HeadResponse', (_message.Message,), {
  'DESCRIPTOR' : _HEADRESPONSE,
  '__module__' : 'chain_pb2'
  # @@protoc_insertion_point(class_scope:chain.HeadResponse)
  })
_sym_db.RegisterMessage(HeadResponse)

GetRequest = _reflection.GeneratedProtocolMessageType('GetRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETREQUEST,
  '__module__' : 'chain_pb2'
  # @@protoc_insertion_point(class_scope:chain.GetRequest)
  })
_sym_db.RegisterMessage(GetRequest)

GetResponse = _reflection.GeneratedProtocolMessageType('GetResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETRESPONSE,
  '__module__' : 'chain_pb2'
  # @@protoc_insertion_point(class_scope:chain.GetResponse)
  })
_sym_db.RegisterMessage(GetResponse)

UpdateRequest = _reflection.GeneratedProtocolMessageType('UpdateRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEREQUEST,
  '__module__' : 'chain_pb2'
  # @@protoc_insertion_point(class_scope:chain.UpdateRequest)
  })
_sym_db.RegisterMessage(UpdateRequest)

UpdateResponse = _reflection.GeneratedProtocolMessageType('UpdateResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATERESPONSE,
  '__module__' : 'chain_pb2'
  # @@protoc_insertion_point(class_scope:chain.UpdateResponse)
  })
_sym_db.RegisterMessage(UpdateResponse)

StateTransferRequest = _reflection.GeneratedProtocolMessageType('StateTransferRequest', (_message.Message,), {

  'StateEntry' : _reflection.GeneratedProtocolMessageType('StateEntry', (_message.Message,), {
    'DESCRIPTOR' : _STATETRANSFERREQUEST_STATEENTRY,
    '__module__' : 'chain_pb2'
    # @@protoc_insertion_point(class_scope:chain.StateTransferRequest.StateEntry)
    })
  ,
  'DESCRIPTOR' : _STATETRANSFERREQUEST,
  '__module__' : 'chain_pb2'
  # @@protoc_insertion_point(class_scope:chain.StateTransferRequest)
  })
_sym_db.RegisterMessage(StateTransferRequest)
_sym_db.RegisterMessage(StateTransferRequest.StateEntry)

StateTransferResponse = _reflection.GeneratedProtocolMessageType('StateTransferResponse', (_message.Message,), {
  'DESCRIPTOR' : _STATETRANSFERRESPONSE,
  '__module__' : 'chain_pb2'
  # @@protoc_insertion_point(class_scope:chain.StateTransferResponse)
  })
_sym_db.RegisterMessage(StateTransferResponse)

AckRequest = _reflection.GeneratedProtocolMessageType('AckRequest', (_message.Message,), {
  'DESCRIPTOR' : _ACKREQUEST,
  '__module__' : 'chain_pb2'
  # @@protoc_insertion_point(class_scope:chain.AckRequest)
  })
_sym_db.RegisterMessage(AckRequest)

AckResponse = _reflection.GeneratedProtocolMessageType('AckResponse', (_message.Message,), {
  'DESCRIPTOR' : _ACKRESPONSE,
  '__module__' : 'chain_pb2'
  # @@protoc_insertion_point(class_scope:chain.AckResponse)
  })
_sym_db.RegisterMessage(AckResponse)


DESCRIPTOR._options = None
_STATETRANSFERREQUEST_STATEENTRY._options = None

_HEADCHAINREPLICA = _descriptor.ServiceDescriptor(
  name='HeadChainReplica',
  full_name='chain.HeadChainReplica',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=509,
  serialized_end=580,
  methods=[
  _descriptor.MethodDescriptor(
    name='increment',
    full_name='chain.HeadChainReplica.increment',
    index=0,
    containing_service=None,
    input_type=_INCREQUEST,
    output_type=_HEADRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_HEADCHAINREPLICA)

DESCRIPTOR.services_by_name['HeadChainReplica'] = _HEADCHAINREPLICA


_TAILCHAINREPLICA = _descriptor.ServiceDescriptor(
  name='TailChainReplica',
  full_name='chain.TailChainReplica',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=582,
  serialized_end=646,
  methods=[
  _descriptor.MethodDescriptor(
    name='get',
    full_name='chain.TailChainReplica.get',
    index=0,
    containing_service=None,
    input_type=_GETREQUEST,
    output_type=_GETRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TAILCHAINREPLICA)

DESCRIPTOR.services_by_name['TailChainReplica'] = _TAILCHAINREPLICA


_REPLICA = _descriptor.ServiceDescriptor(
  name='Replica',
  full_name='chain.Replica',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=649,
  serialized_end=835,
  methods=[
  _descriptor.MethodDescriptor(
    name='update',
    full_name='chain.Replica.update',
    index=0,
    containing_service=None,
    input_type=_UPDATEREQUEST,
    output_type=_UPDATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='stateTransfer',
    full_name='chain.Replica.stateTransfer',
    index=1,
    containing_service=None,
    input_type=_STATETRANSFERREQUEST,
    output_type=_STATETRANSFERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ack',
    full_name='chain.Replica.ack',
    index=2,
    containing_service=None,
    input_type=_ACKREQUEST,
    output_type=_ACKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_REPLICA)

DESCRIPTOR.services_by_name['Replica'] = _REPLICA

# @@protoc_insertion_point(module_scope)
