# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chain_debug_pb2 as chain__debug__pb2


class ChainDebugStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.debug = channel.unary_unary(
                '/chain.ChainDebug/debug',
                request_serializer=chain__debug__pb2.ChainDebugRequest.SerializeToString,
                response_deserializer=chain__debug__pb2.ChainDebugResponse.FromString,
                )


class ChainDebugServicer(object):
    """Missing associated documentation comment in .proto file."""

    def debug(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChainDebugServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'debug': grpc.unary_unary_rpc_method_handler(
                    servicer.debug,
                    request_deserializer=chain__debug__pb2.ChainDebugRequest.FromString,
                    response_serializer=chain__debug__pb2.ChainDebugResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chain.ChainDebug', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChainDebug(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def debug(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chain.ChainDebug/debug',
            chain__debug__pb2.ChainDebugRequest.SerializeToString,
            chain__debug__pb2.ChainDebugResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
